// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("AssembleManagedInstructions")>]
[<assembly: AssemblyProductAttribute("Sacara")>]
[<assembly: AssemblyCompanyAttribute("Enkomio")>]
[<assembly: AssemblyDescriptionAttribute("A VM stack based IR language well suite for code protection.")>]
[<assembly: AssemblyVersionAttribute("2.3.485.0")>]
[<assembly: AssemblyFileVersionAttribute("2.3.485.0")>]
[<assembly: AssemblyInformationalVersionAttribute("2.3.485.0")>]
[<assembly: AssemblyMetadataAttribute("BuildDate","2019-12-03")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "AssembleManagedInstructions"
    let [<Literal>] AssemblyProduct = "Sacara"
    let [<Literal>] AssemblyCompany = "Enkomio"
    let [<Literal>] AssemblyDescription = "A VM stack based IR language well suite for code protection."
    let [<Literal>] AssemblyVersion = "2.3.485.0"
    let [<Literal>] AssemblyFileVersion = "2.3.485.0"
    let [<Literal>] AssemblyInformationalVersion = "2.3.485.0"
    let [<Literal>] AssemblyMetadata_BuildDate = "2019-12-03"
