; This file is auto generated, don't modify it
hash_kernel32_dll EQU 0F8D933CBh
hash_ntdll_dll EQU 0124CAA56h
hash_kernelbase_dll EQU 0B9FCC0AFh
hash_SacaraVm_dll EQU 0F0F093CDh
hash_GetProcessHeap EQU 09C5AA691h
hash_RtlAllocateHeap EQU 0792D5751h
hash_VirtualAlloc EQU 08407647Fh
hash_VirtualFree EQU 02B3E17F4h
hash_VirtualProtect EQU 0BA812C97h
hash_RtlFreeHeap EQU 08190FD3Bh
hash_GetCurrentProcess EQU 0CD8BD9AEh
hash_GetModuleHandleW EQU 0751F945Dh
hash_LoadLibraryA EQU 0C1944D10h
hash_GetModuleInformation EQU 06D3616A7h
