// Implementation file for parser generated by fsyacc
module ES.Sacara.Ir.Parser.SacaraIrParser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open Microsoft.FSharp.Text.Lexing
open Microsoft.FSharp.Text.Parsing.ParseHelpers
# 1 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"


open System
open ES.Sacara.Ir.Parser.IrAst
open ES.Sacara.Ir.Parser.IrParserUtility


# 14 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | INTEGER of (int32)
  | LABEL of (string)
  | IDENTIFIER of (string)
  | STRING of (string)
  | BOOLEAN of (bool)
  | EOF
  | NEWLINE
  | COMMA
  | BYTE
  | WORD
  | DWORD
  | PROC
  | ENDP
  | PUSH
  | POP
  | ADD
  | NOP
  | CALL
  | NCALL
  | WRITE
  | NWRITE
  | READ
  | NREAD
  | GETIP
  | RET
  | JUMP
  | JUMPIFL
  | JUMPIFLE
  | JUMPIFG
  | JUMPIFGE
  | ALLOCA
  | HALT
  | CMP
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_INTEGER
    | TOKEN_LABEL
    | TOKEN_IDENTIFIER
    | TOKEN_STRING
    | TOKEN_BOOLEAN
    | TOKEN_EOF
    | TOKEN_NEWLINE
    | TOKEN_COMMA
    | TOKEN_BYTE
    | TOKEN_WORD
    | TOKEN_DWORD
    | TOKEN_PROC
    | TOKEN_ENDP
    | TOKEN_PUSH
    | TOKEN_POP
    | TOKEN_ADD
    | TOKEN_NOP
    | TOKEN_CALL
    | TOKEN_NCALL
    | TOKEN_WRITE
    | TOKEN_NWRITE
    | TOKEN_READ
    | TOKEN_NREAD
    | TOKEN_GETIP
    | TOKEN_RET
    | TOKEN_JUMP
    | TOKEN_JUMPIFL
    | TOKEN_JUMPIFLE
    | TOKEN_JUMPIFG
    | TOKEN_JUMPIFGE
    | TOKEN_ALLOCA
    | TOKEN_HALT
    | TOKEN_CMP
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startprogram
    | NONTERM_program
    | NONTERM_sourceElementList
    | NONTERM_procDefinition
    | NONTERM_statementList
    | NONTERM_statement
    | NONTERM_statementNoLabel
    | NONTERM_expression

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | INTEGER _ -> 0 
  | LABEL _ -> 1 
  | IDENTIFIER _ -> 2 
  | STRING _ -> 3 
  | BOOLEAN _ -> 4 
  | EOF  -> 5 
  | NEWLINE  -> 6 
  | COMMA  -> 7 
  | BYTE  -> 8 
  | WORD  -> 9 
  | DWORD  -> 10 
  | PROC  -> 11 
  | ENDP  -> 12 
  | PUSH  -> 13 
  | POP  -> 14 
  | ADD  -> 15 
  | NOP  -> 16 
  | CALL  -> 17 
  | NCALL  -> 18 
  | WRITE  -> 19 
  | NWRITE  -> 20 
  | READ  -> 21 
  | NREAD  -> 22 
  | GETIP  -> 23 
  | RET  -> 24 
  | JUMP  -> 25 
  | JUMPIFL  -> 26 
  | JUMPIFLE  -> 27 
  | JUMPIFG  -> 28 
  | JUMPIFGE  -> 29 
  | ALLOCA  -> 30 
  | HALT  -> 31 
  | CMP  -> 32 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_INTEGER 
  | 1 -> TOKEN_LABEL 
  | 2 -> TOKEN_IDENTIFIER 
  | 3 -> TOKEN_STRING 
  | 4 -> TOKEN_BOOLEAN 
  | 5 -> TOKEN_EOF 
  | 6 -> TOKEN_NEWLINE 
  | 7 -> TOKEN_COMMA 
  | 8 -> TOKEN_BYTE 
  | 9 -> TOKEN_WORD 
  | 10 -> TOKEN_DWORD 
  | 11 -> TOKEN_PROC 
  | 12 -> TOKEN_ENDP 
  | 13 -> TOKEN_PUSH 
  | 14 -> TOKEN_POP 
  | 15 -> TOKEN_ADD 
  | 16 -> TOKEN_NOP 
  | 17 -> TOKEN_CALL 
  | 18 -> TOKEN_NCALL 
  | 19 -> TOKEN_WRITE 
  | 20 -> TOKEN_NWRITE 
  | 21 -> TOKEN_READ 
  | 22 -> TOKEN_NREAD 
  | 23 -> TOKEN_GETIP 
  | 24 -> TOKEN_RET 
  | 25 -> TOKEN_JUMP 
  | 26 -> TOKEN_JUMPIFL 
  | 27 -> TOKEN_JUMPIFLE 
  | 28 -> TOKEN_JUMPIFG 
  | 29 -> TOKEN_JUMPIFGE 
  | 30 -> TOKEN_ALLOCA 
  | 31 -> TOKEN_HALT 
  | 32 -> TOKEN_CMP 
  | 35 -> TOKEN_end_of_input
  | 33 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startprogram 
    | 1 -> NONTERM_program 
    | 2 -> NONTERM_sourceElementList 
    | 3 -> NONTERM_sourceElementList 
    | 4 -> NONTERM_procDefinition 
    | 5 -> NONTERM_statementList 
    | 6 -> NONTERM_statementList 
    | 7 -> NONTERM_statement 
    | 8 -> NONTERM_statement 
    | 9 -> NONTERM_statementNoLabel 
    | 10 -> NONTERM_statementNoLabel 
    | 11 -> NONTERM_statementNoLabel 
    | 12 -> NONTERM_statementNoLabel 
    | 13 -> NONTERM_statementNoLabel 
    | 14 -> NONTERM_statementNoLabel 
    | 15 -> NONTERM_statementNoLabel 
    | 16 -> NONTERM_statementNoLabel 
    | 17 -> NONTERM_statementNoLabel 
    | 18 -> NONTERM_statementNoLabel 
    | 19 -> NONTERM_statementNoLabel 
    | 20 -> NONTERM_statementNoLabel 
    | 21 -> NONTERM_statementNoLabel 
    | 22 -> NONTERM_statementNoLabel 
    | 23 -> NONTERM_statementNoLabel 
    | 24 -> NONTERM_statementNoLabel 
    | 25 -> NONTERM_statementNoLabel 
    | 26 -> NONTERM_statementNoLabel 
    | 27 -> NONTERM_statementNoLabel 
    | 28 -> NONTERM_statementNoLabel 
    | 29 -> NONTERM_statementNoLabel 
    | 30 -> NONTERM_statementNoLabel 
    | 31 -> NONTERM_statementNoLabel 
    | 32 -> NONTERM_expression 
    | 33 -> NONTERM_expression 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 35 
let _fsyacc_tagOfErrorTerminal = 33

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | INTEGER _ -> "INTEGER" 
  | LABEL _ -> "LABEL" 
  | IDENTIFIER _ -> "IDENTIFIER" 
  | STRING _ -> "STRING" 
  | BOOLEAN _ -> "BOOLEAN" 
  | EOF  -> "EOF" 
  | NEWLINE  -> "NEWLINE" 
  | COMMA  -> "COMMA" 
  | BYTE  -> "BYTE" 
  | WORD  -> "WORD" 
  | DWORD  -> "DWORD" 
  | PROC  -> "PROC" 
  | ENDP  -> "ENDP" 
  | PUSH  -> "PUSH" 
  | POP  -> "POP" 
  | ADD  -> "ADD" 
  | NOP  -> "NOP" 
  | CALL  -> "CALL" 
  | NCALL  -> "NCALL" 
  | WRITE  -> "WRITE" 
  | NWRITE  -> "NWRITE" 
  | READ  -> "READ" 
  | NREAD  -> "NREAD" 
  | GETIP  -> "GETIP" 
  | RET  -> "RET" 
  | JUMP  -> "JUMP" 
  | JUMPIFL  -> "JUMPIFL" 
  | JUMPIFLE  -> "JUMPIFLE" 
  | JUMPIFG  -> "JUMPIFG" 
  | JUMPIFGE  -> "JUMPIFGE" 
  | ALLOCA  -> "ALLOCA" 
  | HALT  -> "HALT" 
  | CMP  -> "CMP" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | INTEGER _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | LABEL _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | IDENTIFIER _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | STRING _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | BOOLEAN _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | EOF  -> (null : System.Object) 
  | NEWLINE  -> (null : System.Object) 
  | COMMA  -> (null : System.Object) 
  | BYTE  -> (null : System.Object) 
  | WORD  -> (null : System.Object) 
  | DWORD  -> (null : System.Object) 
  | PROC  -> (null : System.Object) 
  | ENDP  -> (null : System.Object) 
  | PUSH  -> (null : System.Object) 
  | POP  -> (null : System.Object) 
  | ADD  -> (null : System.Object) 
  | NOP  -> (null : System.Object) 
  | CALL  -> (null : System.Object) 
  | NCALL  -> (null : System.Object) 
  | WRITE  -> (null : System.Object) 
  | NWRITE  -> (null : System.Object) 
  | READ  -> (null : System.Object) 
  | NREAD  -> (null : System.Object) 
  | GETIP  -> (null : System.Object) 
  | RET  -> (null : System.Object) 
  | JUMP  -> (null : System.Object) 
  | JUMPIFL  -> (null : System.Object) 
  | JUMPIFLE  -> (null : System.Object) 
  | JUMPIFG  -> (null : System.Object) 
  | JUMPIFGE  -> (null : System.Object) 
  | ALLOCA  -> (null : System.Object) 
  | HALT  -> (null : System.Object) 
  | CMP  -> (null : System.Object) 
let _fsyacc_gotos = [| 0us; 65535us; 1us; 65535us; 0us; 1us; 1us; 65535us; 0us; 2us; 2us; 65535us; 0us; 4us; 2us; 5us; 1us; 65535us; 7us; 8us; 2us; 65535us; 7us; 10us; 8us; 11us; 3us; 65535us; 7us; 14us; 8us; 14us; 12us; 13us; 6us; 65535us; 18us; 19us; 22us; 23us; 24us; 25us; 26us; 27us; 28us; 29us; 30us; 31us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 3us; 5us; 8us; 10us; 13us; 17us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 2us; 1us; 3us; 1us; 1us; 1us; 2us; 1us; 3us; 1us; 4us; 1us; 4us; 2us; 4us; 6us; 1us; 4us; 1us; 5us; 1us; 6us; 1us; 7us; 1us; 7us; 1us; 8us; 1us; 9us; 1us; 10us; 1us; 11us; 1us; 12us; 1us; 12us; 1us; 13us; 1us; 13us; 1us; 14us; 1us; 14us; 1us; 15us; 1us; 15us; 1us; 16us; 1us; 16us; 1us; 17us; 1us; 17us; 1us; 18us; 1us; 18us; 1us; 19us; 1us; 20us; 1us; 21us; 1us; 22us; 1us; 23us; 1us; 23us; 1us; 24us; 1us; 24us; 1us; 25us; 1us; 25us; 1us; 26us; 1us; 26us; 1us; 27us; 1us; 28us; 1us; 29us; 1us; 30us; 1us; 31us; 1us; 32us; 1us; 33us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 7us; 9us; 11us; 13us; 15us; 17us; 20us; 22us; 24us; 26us; 28us; 30us; 32us; 34us; 36us; 38us; 40us; 42us; 44us; 46us; 48us; 50us; 52us; 54us; 56us; 58us; 60us; 62us; 64us; 66us; 68us; 70us; 72us; 74us; 76us; 78us; 80us; 82us; 84us; 86us; 88us; 90us; 92us; 94us; 96us; 98us; 100us; 102us; |]
let _fsyacc_action_rows = 51
let _fsyacc_actionTableElements = [|1us; 32768us; 11us; 6us; 0us; 49152us; 2us; 32768us; 5us; 3us; 11us; 6us; 0us; 16385us; 0us; 16386us; 0us; 16387us; 1us; 32768us; 2us; 7us; 24us; 32768us; 1us; 12us; 8us; 38us; 9us; 40us; 10us; 42us; 13us; 18us; 14us; 20us; 15us; 17us; 16us; 16us; 17us; 47us; 18us; 48us; 19us; 34us; 20us; 35us; 21us; 32us; 22us; 33us; 23us; 45us; 24us; 15us; 25us; 22us; 26us; 24us; 27us; 26us; 28us; 28us; 29us; 30us; 30us; 36us; 31us; 46us; 32us; 44us; 25us; 32768us; 1us; 12us; 8us; 38us; 9us; 40us; 10us; 42us; 12us; 9us; 13us; 18us; 14us; 20us; 15us; 17us; 16us; 16us; 17us; 47us; 18us; 48us; 19us; 34us; 20us; 35us; 21us; 32us; 22us; 33us; 23us; 45us; 24us; 15us; 25us; 22us; 26us; 24us; 27us; 26us; 28us; 28us; 29us; 30us; 30us; 36us; 31us; 46us; 32us; 44us; 0us; 16388us; 0us; 16389us; 0us; 16390us; 23us; 32768us; 8us; 38us; 9us; 40us; 10us; 42us; 13us; 18us; 14us; 20us; 15us; 17us; 16us; 16us; 17us; 47us; 18us; 48us; 19us; 34us; 20us; 35us; 21us; 32us; 22us; 33us; 23us; 45us; 24us; 15us; 25us; 22us; 26us; 24us; 27us; 26us; 28us; 28us; 29us; 30us; 30us; 36us; 31us; 46us; 32us; 44us; 0us; 16391us; 0us; 16392us; 0us; 16393us; 0us; 16394us; 0us; 16395us; 2us; 32768us; 0us; 49us; 2us; 50us; 0us; 16396us; 1us; 32768us; 2us; 21us; 0us; 16397us; 2us; 32768us; 0us; 49us; 2us; 50us; 0us; 16398us; 2us; 32768us; 0us; 49us; 2us; 50us; 0us; 16399us; 2us; 32768us; 0us; 49us; 2us; 50us; 0us; 16400us; 2us; 32768us; 0us; 49us; 2us; 50us; 0us; 16401us; 2us; 32768us; 0us; 49us; 2us; 50us; 0us; 16402us; 0us; 16403us; 0us; 16404us; 0us; 16405us; 0us; 16406us; 1us; 32768us; 0us; 37us; 0us; 16407us; 1us; 32768us; 0us; 39us; 0us; 16408us; 1us; 32768us; 0us; 41us; 0us; 16409us; 1us; 32768us; 0us; 43us; 0us; 16410us; 0us; 16411us; 0us; 16412us; 0us; 16413us; 0us; 16414us; 0us; 16415us; 0us; 16416us; 0us; 16417us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 2us; 3us; 6us; 7us; 8us; 9us; 11us; 36us; 62us; 63us; 64us; 65us; 89us; 90us; 91us; 92us; 93us; 94us; 97us; 98us; 100us; 101us; 104us; 105us; 108us; 109us; 112us; 113us; 116us; 117us; 120us; 121us; 122us; 123us; 124us; 125us; 127us; 128us; 130us; 131us; 133us; 134us; 136us; 137us; 138us; 139us; 140us; 141us; 142us; 143us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 2us; 1us; 2us; 4us; 1us; 2us; 2us; 1us; 1us; 1us; 1us; 2us; 2us; 2us; 2us; 2us; 2us; 2us; 1us; 1us; 1us; 1us; 2us; 2us; 2us; 2us; 1us; 1us; 1us; 1us; 1us; 1us; 1us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 2us; 2us; 3us; 4us; 4us; 5us; 5us; 6us; 6us; 6us; 6us; 6us; 6us; 6us; 6us; 6us; 6us; 6us; 6us; 6us; 6us; 6us; 6us; 6us; 6us; 6us; 6us; 6us; 6us; 6us; 7us; 7us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 65535us; 16385us; 16386us; 16387us; 65535us; 65535us; 65535us; 16388us; 16389us; 16390us; 65535us; 16391us; 16392us; 16393us; 16394us; 16395us; 65535us; 16396us; 65535us; 16397us; 65535us; 16398us; 65535us; 16399us; 65535us; 16400us; 65535us; 16401us; 65535us; 16402us; 16403us; 16404us; 16405us; 16406us; 65535us; 16407us; 65535us; 16408us; 65535us; 16409us; 65535us; 16410us; 16411us; 16412us; 16413us; 16414us; 16415us; 16416us; 16417us; |]
let _fsyacc_reductions ()  =    [| 
# 301 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data :  Program )) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (Microsoft.FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startprogram));
# 310 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'sourceElementList)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 26 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                                   Program (List.rev _1) 
                   )
# 26 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 :  Program ));
# 321 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'procDefinition)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 29 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                          [_1] 
                   )
# 29 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'sourceElementList));
# 332 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'sourceElementList)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'procDefinition)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 30 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                                        _2::_1 
                   )
# 30 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'sourceElementList));
# 344 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'statementList)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 33 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                                         procedureDefinition(_2, List.rev _3) 
                   )
# 33 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'procDefinition));
# 356 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'statement)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 36 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                       [_1] 
                   )
# 36 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'statementList));
# 367 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'statementList)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'statement)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 37 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                                 _2::_1 
                   )
# 37 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'statementList));
# 379 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'statementNoLabel)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 40 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                                label(_1, _2) 
                   )
# 40 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'statement));
# 391 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'statementNoLabel)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 41 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                            _1 
                   )
# 41 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'statement));
# 402 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 44 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                  ret() 
                   )
# 44 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'statementNoLabel));
# 412 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 45 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                  nop() 
                   )
# 45 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'statementNoLabel));
# 422 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 46 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                  add() 
                   )
# 46 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'statementNoLabel));
# 432 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'expression)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 47 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                           push(_2) 
                   )
# 47 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'statementNoLabel));
# 443 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 48 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                          pop(_2) 
                   )
# 48 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'statementNoLabel));
# 454 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'expression)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 49 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                           jump(_2) 
                   )
# 49 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'statementNoLabel));
# 465 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'expression)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 50 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                             jumpIf(_2, false, true) 
                   )
# 50 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'statementNoLabel));
# 476 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'expression)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 51 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                              jumpIf(_2, true, true) 
                   )
# 51 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'statementNoLabel));
# 487 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'expression)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 52 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                             jumpIf(_2, false, false) 
                   )
# 52 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'statementNoLabel));
# 498 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'expression)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 53 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                              jumpIf(_2, true, false) 
                   )
# 53 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'statementNoLabel));
# 509 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 54 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                   read() 
                   )
# 54 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'statementNoLabel));
# 519 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 55 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                    readNative() 
                   )
# 55 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'statementNoLabel));
# 529 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 56 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                    write() 
                   )
# 56 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'statementNoLabel));
# 539 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 57 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                    writeNative() 
                   )
# 57 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'statementNoLabel));
# 549 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : int32)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 58 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                          alloca(_2) 
                   )
# 58 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'statementNoLabel));
# 560 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : int32)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 59 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                         memoryByte(_2) 
                   )
# 59 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'statementNoLabel));
# 571 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : int32)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 60 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                         memoryWord(_2) 
                   )
# 60 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'statementNoLabel));
# 582 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : int32)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 61 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                          memoryDword(_2) 
                   )
# 61 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'statementNoLabel));
# 593 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 62 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                  compare() 
                   )
# 62 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'statementNoLabel));
# 603 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 63 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                    getIp() 
                   )
# 63 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'statementNoLabel));
# 613 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 64 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                   halt() 
                   )
# 64 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'statementNoLabel));
# 623 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 65 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                   call() 
                   )
# 65 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'statementNoLabel));
# 633 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 66 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                    callNative() 
                   )
# 66 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'statementNoLabel));
# 643 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int32)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 69 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                     number(_1) 
                   )
# 69 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'expression));
# 654 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 70 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                                                       identifier(_1) 
                   )
# 70 "ES.Sacara.Ir.Parser\SacaraIrParser.fsy"
                 : 'expression));
|]
# 666 "ES.Sacara.Ir.Parser\SacaraIrParser.fs"
let tables () : Microsoft.FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:Microsoft.FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 36;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let program lexer lexbuf :  Program  =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
