// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("EndToEndTests")>]
[<assembly: AssemblyProductAttribute("Sacara")>]
[<assembly: AssemblyCompanyAttribute("Enkomio")>]
[<assembly: AssemblyDescriptionAttribute("A VM stack based IR language well suite for code protection.")>]
[<assembly: AssemblyVersionAttribute("2.4.485.14")>]
[<assembly: AssemblyFileVersionAttribute("2.4.485.14")>]
[<assembly: AssemblyInformationalVersionAttribute("2.4.485.14")>]
[<assembly: AssemblyMetadataAttribute("BuildDate","2019-12-17")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "EndToEndTests"
    let [<Literal>] AssemblyProduct = "Sacara"
    let [<Literal>] AssemblyCompany = "Enkomio"
    let [<Literal>] AssemblyDescription = "A VM stack based IR language well suite for code protection."
    let [<Literal>] AssemblyVersion = "2.4.485.14"
    let [<Literal>] AssemblyFileVersion = "2.4.485.14"
    let [<Literal>] AssemblyInformationalVersion = "2.4.485.14"
    let [<Literal>] AssemblyMetadata_BuildDate = "2019-12-17"
