// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("ES.Sacara.Ir.Assembler")>]
[<assembly: AssemblyProductAttribute("Sacara")>]
[<assembly: AssemblyCompanyAttribute("Enkomio")>]
[<assembly: AssemblyDescriptionAttribute("A VM stack based IR language well suite for code protection.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
[<assembly: AssemblyInformationalVersionAttribute("1.0.0.*")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "ES.Sacara.Ir.Assembler"
    let [<Literal>] AssemblyProduct = "Sacara"
    let [<Literal>] AssemblyCompany = "Enkomio"
    let [<Literal>] AssemblyDescription = "A VM stack based IR language well suite for code protection."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
    let [<Literal>] AssemblyInformationalVersion = "1.0.0.*"
